fn main() {
    // Create placeholders for the sidecar bundle artefacts if they don't exist
    // so that tauri-build's resource-existence check passes during `cargo test`
    // and CI (`pnpm tauri build --no-bundle`). The real files are generated by
    // scripts/pre-bundle-sidecar.sh before `pnpm tauri:build`. The placeholders
    // are gitignored and never ship.
    let manifest_dir = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let tarball = manifest_dir.join("sidecar-bundle.tar.gz");
    if !tarball.exists() {
        let _ = std::fs::write(&tarball, b"");
    }
    // Empty SHA-256 placeholder is tolerated at runtime by
    // `verify_tarball_sha256` (treated as "skip integrity check") and by
    // `read_sidecar_sha256` (falls back to CARGO_PKG_VERSION).
    let sha = manifest_dir.join("sidecar-bundle.sha256");
    if !sha.exists() {
        let _ = std::fs::write(&sha, b"");
    }
    tauri_build::build()
}
