"""
────────────────────────────────────
Server Nexe
Author: Jordi Goy
Location: tests/memory/memory/api/test_store_doc_coherence.py
Description: B066 coherence guard — the knowledge base must teach the canonical
    /v1/memory/store JSON body field ("content"), never the legacy "text" field
    that the endpoint historically rejected with HTTP 422.

www.jgoy.net · https://server-nexe.org
────────────────────────────────────
"""

import json
import re
from pathlib import Path

import pytest


def _repo_root() -> Path:
    """Walk up from this test file until we find the repo root (the dir that
    holds both ``knowledge/`` and ``pytest.ini``)."""
    here = Path(__file__).resolve()
    for parent in here.parents:
        if (parent / "knowledge").is_dir() and (parent / "pytest.ini").is_file():
            return parent
    raise RuntimeError("Could not locate repo root with knowledge/ + pytest.ini")


REPO_ROOT = _repo_root()
KNOWLEDGE = REPO_ROOT / "knowledge"

# Matches a JSON object literal that contains a top-level "text" key, e.g.
#   {"text": "My name is Jordi", "collection": "user_knowledge"}
# or a fenced ```json block. We only flag JSON BODIES (key followed by a value),
# never CLI positional usages like:  ./nexe memory store "text"
_JSON_TEXT_KEY = re.compile(r'\{[^{}]*"text"\s*:')


def _knowledge_markdown_files():
    for path in sorted(KNOWLEDGE.rglob("*.md")):
        # Exclude the embeddings store: it holds stale, already-indexed text and
        # is regenerated by /coherencia-nexe, not hand-authored.
        if ".embeddings" in path.parts:
            continue
        yield path


def _store_curl_blocks(text: str):
    """Yield text spans that are part of a /v1/memory/store invocation.

    We scope the coherence check to the store endpoint so a "text" body for an
    unrelated endpoint elsewhere wouldn't be a false positive. A span runs from
    the mention of ``/v1/memory/store`` to the next blank line / fence / heading.
    """
    lines = text.splitlines()
    n = len(lines)
    i = 0
    while i < n:
        if "/v1/memory/store" in lines[i] or "memory/store" in lines[i]:
            j = i
            block = []
            # Look forward a bounded window for the JSON body of this call.
            while j < n and (j - i) < 12:
                block.append(lines[j])
                j += 1
            yield "\n".join(block)
            i = j
        else:
            i += 1


def test_no_legacy_text_json_body_for_store_in_knowledge():
    """B066: no knowledge doc may teach a {"text": ...} JSON body for
    /v1/memory/store. The endpoint requires "content"; a "text" body 422s.

    Excludes:
      - .embeddings/ (stale, machine-regenerated)
      - CLI positional usages: ./nexe memory store "text"  (correct, NOT a body)
    """
    offenders = []
    for path in _knowledge_markdown_files():
        content = path.read_text(encoding="utf-8")
        for block in _store_curl_blocks(content):
            for m in _JSON_TEXT_KEY.finditer(block):
                snippet = block[m.start():m.start() + 80].replace("\n", " ")
                rel = path.relative_to(REPO_ROOT)
                offenders.append(f"{rel}: {snippet}")

    assert not offenders, (
        "Knowledge docs teach a legacy {\"text\": ...} JSON body for "
        "/v1/memory/store (the endpoint requires \"content\"; a \"text\" body "
        "returns HTTP 422). Offenders:\n" + "\n".join(offenders)
    )


def test_cli_positional_store_usage_is_not_flagged():
    """Guard against the coherence regex over-reaching: a CLI positional usage
    like  ./nexe memory store "text"  is correct and must NOT be flagged.
    """
    cli_line = './nexe memory store "text"   # Save to memory'
    assert not _JSON_TEXT_KEY.search(cli_line)
