"""
────────────────────────────────────
Server Nexe
Author: Jordi Goy
Location: tests/test_endpoints_auth.py
Description: Bug 22 — Verifies that sensitive endpoints are protected by X-API-Key.
             Without API key -> 401/403. With valid API key -> NOT 401/403 (may be 200/4xx/5xx).

www.jgoy.net · https://server-nexe.org
────────────────────────────────────
"""

import os
import pytest


# Sensitive GET endpoints that must be protected by X-API-Key (Bug 22).
PROTECTED_ENDPOINTS = [
    "/metrics",
    "/metrics/health",
    "/metrics/json",
    "/modules",
    "/api/bootstrap/info",
    "/ollama/api/models",
    "/ollama/health",
    "/ollama/info",
    "/memory/health",
    "/memory/info",
    "/memory/stats/test-user",
    "/memory/profile/test-user",
    "/rag/health",
    "/rag/info",
    "/rag/files/stats",
    # Audit r4 B2: info/health for mlx, llama-cpp, security
    "/mlx/info",
    "/llama-cpp/info",
    "/security/info",
    "/security/health",
]

# Fix Consultor pass 1 — Finding 3: incomplete Bug 22 coverage.
# Extended with protected POST/DELETE. Each entry: (method, path, body_json).
# Item 24 surgery 2026-04-08: /ollama/api/chat REMOVED (single pipeline).
# /mlx/chat and /llama-cpp/chat REMOVED. Dropped here for consistency.
PROTECTED_WRITE_ENDPOINTS = [
    ("POST", "/ollama/api/pull", {"name": "dummy-model"}),
    ("DELETE", "/ollama/api/models/dummy-model", None),
    ("POST", "/rag/document", {"text": "dummy", "metadata": {}}),
    ("POST", "/rag/search", {"query": "dummy"}),
]


@pytest.fixture(autouse=True)
def _disable_dev_mode_bypass(monkeypatch, admin_api_key):
    """Ensures the dev bypass does not activate accidentally and the API key matches."""
    monkeypatch.setenv("NEXE_DEV_MODE", "false")
    monkeypatch.delenv("NEXE_DEV_MODE_ALLOW_REMOTE", raising=False)
    # Sync NEXE_PRIMARY_API_KEY with the one generated by the global conftest fixture,
    # since load_api_keys() is read dynamically on each request.
    monkeypatch.setenv("NEXE_PRIMARY_API_KEY", admin_api_key)
    monkeypatch.delenv("NEXE_PRIMARY_KEY_EXPIRES", raising=False)


# TrustedHostMiddleware only allows localhost/127.0.0.1; the Host header must be overridden.
_HOST = {"Host": "localhost"}


@pytest.mark.parametrize("path", PROTECTED_ENDPOINTS)
def test_protected_endpoint_without_key_rejected(client, path):
    """Bug 22: without X-API-Key -> 401 or 403."""
    r = client.get(path, headers=_HOST)
    assert r.status_code in (401, 403), (
        f"{path}: expected 401/403 without API key, got {r.status_code}: {r.text[:200]}"
    )


@pytest.mark.parametrize("path", PROTECTED_ENDPOINTS)
def test_protected_endpoint_with_key_not_unauthorized(client, auth_headers, path):
    """Bug 22: with a valid X-API-Key must NOT be 401/403 (may be 200/404/500/503 depending on service)."""
    headers = {**auth_headers, **_HOST}
    r = client.get(path, headers=headers)
    assert r.status_code not in (401, 403), (
        f"{path}: valid API key but got {r.status_code}: {r.text[:200]}"
    )


@pytest.mark.parametrize("method,path,body", PROTECTED_WRITE_ENDPOINTS)
def test_protected_write_endpoint_without_key_rejected(client, method, path, body):
    """Fix Consultor — Finding 3: POST/DELETE without X-API-Key -> 401/403."""
    kwargs = {"headers": _HOST}
    if body is not None:
        kwargs["json"] = body
    r = client.request(method, path, **kwargs)
    assert r.status_code in (401, 403), (
        f"{method} {path}: expected 401/403 without API key, "
        f"got {r.status_code}: {r.text[:200]}"
    )


def _get_csrf_headers(client):
    """
    Makes an initial GET to obtain the CSRF cookie and returns headers with
    X-CSRF-Token. Required for POST/DELETE endpoints not exempt from
    CSRF (e.g. /ollama/api/*). The /rag/ and /v1/ endpoints are on the
    exemptions list (core/middleware.py), but /ollama/ is not.
    """
    # Trigger CSRF cookie set — any GET works
    client.get("/health", headers=_HOST)
    cookie = client.cookies.get("nexe_csrf_token")
    if cookie:
        return {"X-CSRF-Token": cookie}
    return {}


@pytest.mark.parametrize("method,path,body", PROTECTED_WRITE_ENDPOINTS)
def test_protected_write_endpoint_with_key_not_unauthorized(
    client, auth_headers, method, path, body
):
    """Fix Consultor — Finding 3: POST/DELETE with X-API-Key must NOT be 401/403."""
    csrf = _get_csrf_headers(client)
    kwargs = {"headers": {**auth_headers, **_HOST, **csrf}}
    if body is not None:
        kwargs["json"] = body
    r = client.request(method, path, **kwargs)
    assert r.status_code not in (401, 403), (
        f"{method} {path}: valid API key but got {r.status_code}: {r.text[:200]}"
    )


def test_docs_endpoints_disabled_in_production():
    """Bug 22: with NEXE_ENV=production the /docs and /openapi.json endpoints are not exposed."""
    from fastapi.testclient import TestClient
    from fastapi import FastAPI

    # Create a FastAPI instance directly simulating the same config as factory_app.py
    # to avoid affecting the global pytest session.
    saved = os.environ.get("NEXE_ENV")
    try:
        os.environ["NEXE_ENV"] = "production"
        # Reproduïm la lògica que aplica factory_app.create_fastapi_instance
        _docs_enabled = os.environ["NEXE_ENV"].lower() in ("development", "test")
        app = FastAPI(
            docs_url="/docs" if _docs_enabled else None,
            redoc_url="/redoc" if _docs_enabled else None,
            openapi_url="/openapi.json" if _docs_enabled else None,
        )
        with TestClient(app) as c:
            assert c.get("/docs").status_code == 404
            assert c.get("/openapi.json").status_code == 404
            assert c.get("/redoc").status_code == 404
    finally:
        if saved is None:
            os.environ.pop("NEXE_ENV", None)
        else:
            os.environ["NEXE_ENV"] = saved


def test_docs_endpoints_enabled_in_development():
    """Bug 22: with NEXE_ENV=development the /docs and /openapi.json endpoints are exposed."""
    from fastapi.testclient import TestClient
    from fastapi import FastAPI

    saved = os.environ.get("NEXE_ENV")
    try:
        os.environ["NEXE_ENV"] = "development"
        _docs_enabled = os.environ["NEXE_ENV"].lower() in ("development", "test")
        app = FastAPI(
            docs_url="/docs" if _docs_enabled else None,
            redoc_url="/redoc" if _docs_enabled else None,
            openapi_url="/openapi.json" if _docs_enabled else None,
        )
        with TestClient(app) as c:
            assert c.get("/openapi.json").status_code == 200
    finally:
        if saved is None:
            os.environ.pop("NEXE_ENV", None)
        else:
            os.environ["NEXE_ENV"] = saved
