// ModelCatalog.swift — Model catalog loaded from JSON (generated by export_catalog_json.py)

import Foundation

struct AIModel: Codable, Identifiable {
    let key: String
    let name: String
    let origin: String
    let year: Int?
    let role: String?
    let params: String
    let diskGB: Double
    let ramGB: Double
    let description: [String: String]
    let mlx: Bool?
    let ollama: String?
    let gguf: String?
    let iberic: Bool?

    var id: String { key }

    enum CodingKeys: String, CodingKey {
        case key, name, origin, year, role, params, description, mlx, ollama, gguf, iberic
        case diskGB = "disk_gb"
        case ramGB  = "ram_gb"
    }

    /// Returns the engines available for this model
    var availableEngines: [String] {
        var engines: [String] = []
        if mlx == true { engines.append("mlx") }
        if ollama != nil { engines.append("ollama") }
        if gguf != nil { engines.append("llama_cpp") }
        return engines
    }

    /// Picks the recommended engine (MLX > Ollama > llama_cpp)
    func recommendedEngine(isAppleSilicon: Bool) -> String {
        if isAppleSilicon, mlx == true { return "mlx" }
        if ollama != nil { return "ollama" }
        if gguf != nil { return "llama_cpp" }
        return "ollama"
    }

    /// Localized description
    func localizedDescription(lang: Lang) -> String {
        return description[lang.rawValue] ?? description["en"] ?? ""
    }

    /// Whether the model has visual capability (VLM). Derived from the descriptions.
    /// Whole-word matching (avoids "visible" → false positive).
    /// TODO: formalize with a `vision: bool` flag in the Python catalog.
    var hasVision: Bool {
        let vlmWords: Set<String> = [
            "visió", "visio",        // ca
            "visión", "vision",      // es/en
            "multimodal",            // universal
            "vl",                    // common tag (VLM, VL models)
            "vlm",
        ]
        let separators = CharacterSet.alphanumerics.inverted
        for desc in description.values {
            let words = desc.lowercased().components(separatedBy: separators)
            for w in words where vlmWords.contains(w) {
                return true
            }
        }
        return false
    }

    /// Creates a custom model from an Ollama name
    static func customOllama(_ name: String) -> AIModel {
        return AIModel(
            key: "custom_ollama_\(name)",
            name: name,
            origin: "Ollama",
            year: nil,
            role: "custom",
            params: "—",
            diskGB: 0,
            ramGB: 0,
            description: ["ca": "Model personalitzat", "es": "Modelo personalizado", "en": "Custom model"],
            mlx: false,
            ollama: name,
            gguf: nil,
            iberic: false
        )
    }

    /// Creates a custom model from a Hugging Face repo (GGUF)
    static func customHuggingFace(_ repo: String) -> AIModel {
        let shortName = repo.components(separatedBy: "/").last ?? repo
        return AIModel(
            key: "custom_hf_\(repo)",
            name: shortName,
            origin: "Hugging Face",
            year: nil,
            role: "custom",
            params: "—",
            diskGB: 0,
            ramGB: 0,
            description: ["ca": repo, "es": repo, "en": repo],
            mlx: false,
            ollama: nil,
            gguf: repo,
            iberic: false
        )
    }
}

struct ModelCatalog: Codable {
    var tier8: [AIModel]  = []
    var tier16: [AIModel] = []
    var tier24: [AIModel] = []
    var tier32: [AIModel] = []
    var tier48: [AIModel] = []
    var tier64: [AIModel] = []

    enum CodingKeys: String, CodingKey {
        case tier8   = "tier_8"
        case tier16  = "tier_16"
        case tier24  = "tier_24"
        case tier32  = "tier_32"
        case tier48  = "tier_48"
        case tier64  = "tier_64"
    }

    init(tier8: [AIModel] = [], tier16: [AIModel] = [], tier24: [AIModel] = [],
         tier32: [AIModel] = [], tier48: [AIModel] = [], tier64: [AIModel] = []) {
        self.tier8 = tier8; self.tier16 = tier16; self.tier24 = tier24
        self.tier32 = tier32; self.tier48 = tier48; self.tier64 = tier64
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)

        // A tier that is ABSENT from the JSON is legitimate — not every build ships
        // every tier. A tier that is PRESENT but does not decode is corruption, and
        // swallowing it would drop models from the picker with nothing to show for it.
        func tier(_ key: CodingKeys) throws -> [AIModel] {
            guard c.contains(key) else { return [] }
            return try c.decode([AIModel].self, forKey: key)
        }

        tier8  = try tier(.tier8)
        tier16 = try tier(.tier16)
        tier24 = try tier(.tier24)
        tier32 = try tier(.tier32)
        tier48 = try tier(.tier48)
        tier64 = try tier(.tier64)
    }

    /// Why the catalog could not be loaded. An empty picker with no explanation is a
    /// bug, not a state: whoever loads the catalog has to say which of these happened.
    enum LoadFailure: Error {
        /// models.json is in neither of the two places we look.
        case notFound(searched: [String])
        /// The file is there but unreadable (permissions, truncated read).
        case unreadable(path: String, underlying: Error)
        /// The file is there and readable but is not a valid catalog.
        case corrupt(path: String, underlying: Error)

        /// One line, meant for both the log and the wizard banner.
        var summary: String {
            switch self {
            case .notFound(let searched):
                return "models.json not found (looked in: \(searched.joined(separator: ", ")))"
            case .unreadable(let path, let underlying):
                return "models.json unreadable at \(path): \(underlying)"
            case .corrupt(let path, let underlying):
                return "models.json is not a valid catalog at \(path): \(underlying)"
            }
        }
    }

    /// Loads the catalog, reporting WHY it failed instead of returning an empty one.
    ///
    /// Two sources are tried in order — the bundle Resources, then next to the binary
    /// for `swift run` during development. "Missing in both" and "present but broken"
    /// are different problems and used to look identical: an empty picker.
    static func loadOrFail() -> Result<ModelCatalog, LoadFailure> {
        var searched: [String] = []

        // The bundle Resources (the shipped installer).
        if let url = Bundle.main.url(forResource: "models", withExtension: "json") {
            return decodeCatalog(at: url)
        }
        searched.append("bundle Resources")

        // Next to the binary (development).
        let binaryDir = URL(fileURLWithPath: CommandLine.arguments[0]).deletingLastPathComponent()
        let devPath = binaryDir.appendingPathComponent("models.json")
        if FileManager.default.fileExists(atPath: devPath.path) {
            return decodeCatalog(at: devPath)
        }
        searched.append(devPath.path)

        return .failure(.notFound(searched: searched))
    }

    private static func decodeCatalog(at url: URL) -> Result<ModelCatalog, LoadFailure> {
        let data: Data
        do {
            data = try Data(contentsOf: url)
        } catch {
            return .failure(.unreadable(path: url.path, underlying: error))
        }
        do {
            return .success(try JSONDecoder().decode(ModelCatalog.self, from: data))
        } catch {
            return .failure(.corrupt(path: url.path, underlying: error))
        }
    }

    /// All models in a flat array
    var allModels: [AIModel] {
        return tier8 + tier16 + tier24 + tier32 + tier48 + tier64
    }

    /// Models of a tier (keys: "tier_8", "tier_16", ..., "tier_64")
    func models(for tier: String) -> [AIModel] {
        switch tier {
        case "tier_8":   return tier8
        case "tier_16":  return tier16
        case "tier_24":  return tier24
        case "tier_32":  return tier32
        case "tier_48":  return tier48
        case "tier_64":  return tier64
        default:         return []
        }
    }
}
