"""
────────────────────────────────────
Server Nexe
Location: installer/installer_catalog_data.py
Description: Model catalog data (MODEL_CATALOG).
────────────────────────────────────
"""

# ═══════════════════════════════════════════════════════════════════════════
# MODEL CATALOG - Multiple options per category, including Catalan models
# Engines: mlx (Apple Silicon), ollama (universal)
# ═══════════════════════════════════════════════════════════════════════════
MODEL_CATALOG = {
    # ─────────────────────────────────────────────────────────────────────────
    # SMALL MODELS - For 8GB RAM machines
    # ─────────────────────────────────────────────────────────────────────────
    "small": [
        {
            "key": "qwen35_4b",
            "name": "Qwen3.5 4B",
            "origin": "Alibaba",
            "year": 2026,
            "lang": {"ca": "Multilingüe (excel·lent català)", "es": "Multilingüe (excelente catalán)", "en": "Multilingual (excellent Catalan)"},
            "params": "4B",
            "disk_gb": 3.4,
            "ram_gb": 4.0,
            "description": {"ca": "Multimodal, tool calling, thinking. Ideal per Macs amb 8 GB", "es": "Multimodal, tool calling, thinking. Ideal para Macs con 8 GB", "en": "Multimodal, tool calling, thinking. Ideal for 8 GB Macs"},
            "mlx": "mlx-community/Qwen3.5-4B-4bit",
            "ollama": "qwen3.5:4b",
            "gguf": None,
            "chat_format": "chatml",
            "prompt_tier": "small",
        },
        {
            "key": "qwen35_2b",
            "name": "Qwen3.5 2B",
            "origin": "Alibaba",
            "year": 2026,
            "lang": {"ca": "Multilingüe +100 idiomes", "es": "Multilingüe +100 idiomas", "en": "Multilingual +100 languages"},
            "params": "2B",
            "disk_gb": 1.5,
            "ram_gb": 2.0,
            "description": {"ca": "Multimodal, tool calling i thinking (requereix think:true)", "es": "Multimodal, tool calling y thinking (requiere think:true)", "en": "Multimodal, tool calling and thinking (requires think:true)"},
            "mlx": "mlx-community/Qwen3.5-2B-4bit",
            "ollama": "qwen3.5:2b",
            "gguf": None,
            "chat_format": "chatml",
            "prompt_tier": "small",
        },
        # Phi-3.5 retirat del catàleg (Bug 29):
        # la URL GGUF de Microsoft requereix login HF i descarregava
        # 29 bytes (HTML d'error) provocant falles silencioses durant la instal·lació.
        {
            "key": "salamandra2b",
            "name": "Salamandra 2B",
            "origin": "BSC/AINA (Catalunya)",
            "year": 2025,
            "lang": {"ca": "Català, Castellà, Euskera, Gallec", "es": "Catalán, Castellano, Euskera, Gallego", "en": "Catalan, Spanish, Basque, Galician"},
            "params": "2B",
            "disk_gb": 1.5,
            "ram_gb": 2.5,
            "description": {"ca": "Optimitzat per llengües ibèriques", "es": "Optimizado para lenguas ibéricas", "en": "Optimized for Iberian languages"},
            # Salamandra 2B NO té port MLX publicat a mlx-community (verificat
            # HF API 2026-04-14). A Mac Apple Silicon cau a Ollama via auto.
            "mlx": None,
            "ollama": "hdnh2006/salamandra-2b-instruct",
            "gguf": None,
            "chat_format": "chatml",
            "prompt_tier": "small",
        },
        {
            "key": "gemma4_e4b",
            "name": "Gemma 4 E4B",
            "origin": "Google",
            "year": 2026,
            "lang": {"ca": "Multilingüe", "es": "Multilingüe", "en": "Multilingual"},
            "params": "8B totals / ~4-8B efectius (MoE)",
            "disk_gb": 4.5,
            "ram_gb": 5.0,
            "description": {"ca": "Multimodal, thinking configurable, visió (imatge i àudio). Excel·lent per creativitat i anàlisi visual.", "es": "Multimodal, thinking configurable, visión (imagen y audio). Excelente para creatividad y análisis visual.", "en": "Multimodal, configurable thinking, vision (image and audio). Excellent for creativity and visual analysis."},
            "mlx": "mlx-community/gemma-4-e4b-it-4bit",
            "ollama": "gemma4:e4b",
            "gguf": None,
            "chat_format": "chatml",
            "prompt_tier": "full",
        },
    ],
    # ─────────────────────────────────────────────────────────────────────────
    # MEDIUM MODELS - For 12-16GB RAM machines
    # ─────────────────────────────────────────────────────────────────────────
    "medium": [
        {
            "key": "mistral7b",
            "name": "Mistral 7B",
            "origin": "Mistral AI (França)",
            "year": 2023,
            "lang": {"ca": "Multilingüe", "es": "Multilingüe", "en": "Multilingual"},
            "params": "7B",
            "disk_gb": 4.1,
            "ram_gb": 5.5,
            "description": {"ca": "Excel·lent equilibri qualitat/velocitat", "es": "Excelente equilibrio calidad/velocidad", "en": "Excellent quality/speed balance"},
            "mlx": "mlx-community/Mistral-7B-Instruct-v0.3-4bit",
            "ollama": "mistral:latest",
            "gguf": "https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GGUF/resolve/main/mistral-7b-instruct-v0.2.Q4_K_M.gguf",
            "chat_format": "chatml",  # 'mistral' no vàlid a llama.cpp; chatml suporta system msgs (RAG)
            "prompt_tier": "full",
        },
        {
            "key": "salamandra7b",
            "name": "Salamandra 7B",
            "origin": "BSC/AINA (Catalunya)",
            "year": 2025,
            "lang": {"ca": "Català, Castellà, Euskera, Gallec", "es": "Catalán, Castellano, Euskera, Gallego", "en": "Catalan, Spanish, Basque, Galician"},
            "params": "7B",
            "disk_gb": 4.9,
            "ram_gb": 6.5,
            "description": {"ca": "El millor per català i llengües ibèriques", "es": "El mejor para catalán y lenguas ibéricas", "en": "Best for Catalan and Iberian languages"},
            "mlx": None,
            "ollama": "hdnh2006/salamandra-7b-instruct:q4_K_M",  # testat i verificat
            "gguf": "https://huggingface.co/hdnh2006/BSC-LT-salamandra-7b-instruct-gguf/resolve/main/salamandra-7b-instruct-Q4_K_M.gguf",
            "chat_format": "chatml",
            "prompt_tier": "full",
        },
        {
            "key": "gemma3_12b",
            "name": "Gemma 3 12B",
            "origin": "Google DeepMind",
            "year": 2025,
            "lang": {"ca": "Multilingüe (excel·lent català)", "es": "Multilingüe (excelente catalán)", "en": "Multilingual (excellent Catalan)"},
            "params": "12B",
            "disk_gb": 7.0,
            "ram_gb": 9.0,
            "description": {"ca": "Molt bon seguiment d'instruccions i RAG", "es": "Muy buen seguimiento de instrucciones y RAG", "en": "Excellent instruction following and RAG"},
            "mlx": "mlx-community/gemma-3-12b-it-4bit",
            "ollama": "gemma3:12b",
            "gguf": None,
            "chat_format": "chatml",
            "prompt_tier": "full",
        },
        {
            "key": "llama4_scout",
            "name": "Llama 4 Scout",
            "origin": "Meta",
            "year": 2026,
            "lang": {"ca": "Multilingüe", "es": "Multilingüe", "en": "Multilingual"},
            "params": "109B totals / 17B actius (MoE)",
            "disk_gb": 7.5,
            "ram_gb": 8.0,
            "description": {"ca": "Context de 10 milions de tokens. Thinking fort i visió nativa.", "es": "Contexto de 10 millones de tokens. Thinking fuerte y visión nativa.", "en": "10 million token context. Strong thinking and native vision."},
            "mlx": "mlx-community/Llama-4-Scout-17B-16E-Instruct-4bit",
            "ollama": "llama4:scout",
            "gguf": None,
            "chat_format": "chatml",
            "prompt_tier": "full",
        },
        {
            "key": "qwen35_9b",
            "name": "Qwen3.5 9B",
            "origin": "Alibaba",
            "year": 2026,
            "lang": {"ca": "Multilingüe (excel·lent català)", "es": "Multilingüe (excelente catalán)", "en": "Multilingual (excellent Catalan)"},
            "params": "9B",
            "disk_gb": 6.6,
            "ram_gb": 8.0,
            "description": {"ca": "Multimodal, thinking, tool calling. Millor relacio qualitat/mida de la familia. Apache 2.0", "es": "Multimodal, thinking, tool calling. Mejor relacion calidad/tamaño de la familia. Apache 2.0", "en": "Multimodal, thinking, tool calling. Best quality/size ratio of the family. Apache 2.0"},
            "mlx": "mlx-community/Qwen3.5-9B-4bit",
            "ollama": "qwen3.5:9b",
            "gguf": None,
            "chat_format": "chatml",
            "prompt_tier": "full",
        },
    ],
    # ─────────────────────────────────────────────────────────────────────────
    # LARGE MODELS - For 32GB+ RAM machines
    # ─────────────────────────────────────────────────────────────────────────
    "large": [
        {
            "key": "qwen35_27b",
            "name": "Qwen3.5 27B",
            "origin": "Alibaba",
            "year": 2026,
            "lang": {"ca": "Multilingüe (excel·lent català)", "es": "Multilingüe (excelente catalán)", "en": "Multilingual (excellent Catalan)"},
            "params": "27B",
            "disk_gb": 17.0,
            "ram_gb": 20,
            "description": {"ca": "Multimodal complet, thinking avançat, tool calling. El millor Qwen per RAG i català. Apache 2.0", "es": "Multimodal completo, thinking avanzado, tool calling. El mejor Qwen para RAG y catalán. Apache 2.0", "en": "Full multimodal, advanced thinking, tool calling. Best Qwen for RAG and Catalan. Apache 2.0"},
            "mlx": "mlx-community/Qwen3.5-27B-4bit",
            "ollama": "qwen3.5:27b",
            "gguf": None,
            "chat_format": "chatml",
            "prompt_tier": "full",
        },
        {
            "key": "gemma3_27b",
            "name": "Gemma 3 27B",
            "origin": "Google DeepMind",
            "year": 2025,
            "lang": {"ca": "Multilingüe (excel·lent català)", "es": "Multilingüe (excelente catalán)", "en": "Multilingual (excellent Catalan)"},
            "params": "27B",
            "disk_gb": 16.2,
            "ram_gb": 20,
            "description": {"ca": "Excel·lent memòria RAG i català. Testat i recomanat", "es": "Excelente memoria RAG y catalán. Testado y recomendado", "en": "Excellent RAG memory and Catalan. Tested and recommended"},
            "mlx": "mlx-community/gemma-3-27b-it-4bit",
            "ollama": "gemma3:27b",
            "gguf": None,
            "chat_format": "chatml",
            "prompt_tier": "full",
        },
        {
            "key": "gpt_oss_20b",
            "name": "GPT-OSS 20B",
            "origin": "OpenAI (Open Source)",
            "year": 2025,
            "lang": {"ca": "Multilingüe", "es": "Multilingüe", "en": "Multilingual"},
            "params": "21B (MoE, 3.6B actius)",
            "disk_gb": 22.2,
            "ram_gb": 24,
            "description": {"ca": "Model obert d'OpenAI, MoE eficient. Llicència Apache 2.0", "es": "Modelo abierto de OpenAI, MoE eficiente. Licencia Apache 2.0", "en": "OpenAI open model, efficient MoE. Apache 2.0 license"},
            "mlx": "lmstudio-community/gpt-oss-20b-MLX-8bit",
            "ollama": "gpt-oss:20b",
            "gguf": None,
            "chat_format": "chatml",
            "prompt_tier": "full",
        },
        {
            "key": "qwen25_32b",
            "name": "Qwen2.5 32B",
            "origin": "Alibaba",
            "year": 2024,
            "lang": {"ca": "Multilingüe (excel·lent multi-idioma)", "es": "Multilingüe (excelente multi-idioma)", "en": "Multilingual (excellent multi-language)"},
            "params": "32B",
            "disk_gb": 19.0,
            "ram_gb": 22,
            "description": {"ca": "Excel·lent en multi-idioma i seguiment d'instruccions", "es": "Excelente en multi-idioma y seguimiento de instrucciones", "en": "Excellent multilingual and instruction following"},
            "mlx": "mlx-community/Qwen2.5-32B-Instruct-4bit",
            "ollama": "qwen2.5:32b",
            "gguf": "https://huggingface.co/bartowski/Qwen2.5-32B-Instruct-GGUF/resolve/main/Qwen2.5-32B-Instruct-Q4_K_M.gguf",
            "chat_format": "chatml",
            "prompt_tier": "full",
        },
        {
            "key": "qwq_32b",
            "name": "QwQ 32B",
            "origin": "Alibaba",
            "year": 2025,
            "lang": {"ca": "Multilingüe (raonament avançat)", "es": "Multilingüe (razonamiento avanzado)", "en": "Multilingual (advanced reasoning)"},
            "params": "32B",
            "disk_gb": 19.0,
            "ram_gb": 22,
            "description": {"ca": "Especialitzat en raonament — pensa pas a pas. Compita amb models molt més grans", "es": "Especializado en razonamiento — piensa paso a paso. Compite con modelos mucho más grandes", "en": "Reasoning specialist — thinks step by step. Competes with much larger models"},
            "mlx": "mlx-community/QwQ-32B-4bit",
            "ollama": "qwq:32b",
            "gguf": None,
            "chat_format": "chatml",
            "prompt_tier": "full",
        },
        {
            # Key alineada amb Swift wizard models.json (2026-04-14).
            # Abans "deepseek_r1_32b"; és el mateix model (distill Qwen 32B).
            "key": "deepseek_r1_distill_32b",
            "name": "DeepSeek R1 Distill 32B",
            "origin": "DeepSeek AI (Xina)",
            "year": 2025,
            "lang": {"ca": "Multilingüe (raonament avançat)", "es": "Multilingüe (razonamiento avanzado)", "en": "Multilingual (advanced reasoning)"},
            "params": "32B (Distill Qwen)",
            "disk_gb": 19.0,
            "ram_gb": 22,
            "description": {"ca": "Model de raonament — pensa abans de respondre. Ideal per anàlisi i documents", "es": "Modelo de razonamiento — piensa antes de responder. Ideal para análisis y documentos", "en": "Reasoning model — thinks before answering. Ideal for analysis and documents"},
            "mlx": "mlx-community/DeepSeek-R1-Distill-Qwen-32B-4bit",
            "ollama": "deepseek-r1:32b",
            "gguf": "https://huggingface.co/bartowski/DeepSeek-R1-Distill-Qwen-32B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-32B-Q4_K_M.gguf",
            "chat_format": "chatml",
            "prompt_tier": "full",
        },
        {
            "key": "qwen35_35b_moe",
            "name": "Qwen3.5 35B-A3B",
            "origin": "Alibaba",
            "year": 2026,
            "lang": {"ca": "Multilingüe (excel·lent català)", "es": "Multilingüe (excelente catalán)", "en": "Multilingual (excellent Catalan)"},
            "params": "35B totals / 3B actius (MoE)",
            "disk_gb": 21.0,
            "ram_gb": 21,
            "description": {"ca": "Velocitat de 9B amb qualitat de 35B. Thinking excel·lent. Apache 2.0.", "es": "Velocidad de 9B con calidad de 35B. Thinking excelente. Apache 2.0.", "en": "9B speed with 35B quality. Excellent thinking. Apache 2.0."},
            "mlx": "mlx-community/Qwen3.5-35B-A3B-4bit",
            "ollama": "qwen3.5:35b-a3b",
            "gguf": None,
            "chat_format": "chatml",
            "prompt_tier": "full",
        },
        {
            "key": "gemma4_31b",
            "name": "Gemma 4 31B",
            "origin": "Google",
            "year": 2026,
            "lang": {"ca": "Multilingüe", "es": "Multilingüe", "en": "Multilingual"},
            "params": "31B (dense)",
            "disk_gb": 18.5,
            "ram_gb": 18,
            "description": {"ca": "Alternativa potent en raonament i visió. Context 256K. Thinking excel·lent.", "es": "Alternativa potente en razonamiento y visión. Contexto 256K. Thinking excelente.", "en": "Powerful reasoning and vision alternative. 256K context. Excellent thinking."},
            "mlx": "mlx-community/gemma-4-31b-it-4bit",
            "ollama": "gemma4:31b",
            "gguf": None,
            "chat_format": "chatml",
            "prompt_tier": "full",
        },
        {
            "key": "alia_40b",
            "name": "ALIA-40B Instruct",
            "origin": "BSC (Catalunya)",
            "year": 2026,
            "lang": {"ca": "Llengües ibèriques (9 idiomes)", "es": "Lenguas ibéricas (9 idiomas)", "en": "Iberian languages (9)"},
            "params": "40B",
            "disk_gb": 24.0,
            "ram_gb": 24,
            "description": {"ca": "Model públic multilingüe avançat fet a Europa. 9 idiomes ibèrics. Només llama.cpp.", "es": "Modelo público multilingüe avanzado hecho en Europa. 9 idiomas ibéricos. Solo llama.cpp.", "en": "Advanced public multilingual model made in Europe. 9 Iberian languages. llama.cpp only."},
            "mlx": None,
            "ollama": None,
            "gguf": "https://huggingface.co/BSC-LT/ALIA-40b-instruct-2601-GGUF/resolve/main/ALIA-40b-instruct-2601-Q8_0.gguf",
            "chat_format": "chatml",
            "prompt_tier": "full",
        },
        {
            "key": "llama4_maverick",
            "name": "Llama 4 Maverick",
            "origin": "Meta",
            "year": 2026,
            "lang": {"ca": "Multilingüe", "es": "Multilingüe", "en": "Multilingual"},
            "params": "400B totals / 17B actius (MoE)",
            "disk_gb": 42.0,
            "ram_gb": 38,
            "description": {"ca": "Multimodal i context enorme (~1M tokens). Thinking fort i visió nativa.", "es": "Multimodal y contexto enorme (~1M tokens). Thinking fuerte y visión nativa.", "en": "Multimodal and huge context (~1M tokens). Strong thinking and native vision."},
            "mlx": "mlx-community/Llama-4-Maverick-17B-128E-Instruct-4bit",
            "ollama": "llama4:maverick",
            "gguf": None,
            "chat_format": "chatml",
            "prompt_tier": "full",
        },
        {
            "key": "qwen35_122b_moe",
            "name": "Qwen3.5 122B-A10B",
            "origin": "Alibaba",
            "year": 2026,
            "lang": {"ca": "Multilingüe (excel·lent català)", "es": "Multilingüe (excelente catalán)", "en": "Multilingual (excellent Catalan)"},
            "params": "122B totals / 10B actius (MoE)",
            "disk_gb": 50.0,
            "ram_gb": 48,
            "description": {"ca": "Màxim per a codi i agents. Thinking excel·lent. Apache 2.0.", "es": "Máximo para código y agentes. Thinking excelente. Apache 2.0.", "en": "Maximum for code and agents. Excellent thinking. Apache 2.0."},
            "mlx": "mlx-community/Qwen3.5-122B-A10B-4bit",
            "ollama": "qwen3.5:122b-a10b",
            "gguf": None,
            "chat_format": "chatml",
            "prompt_tier": "full",
        },
        {
            "key": "gpt_oss_120b",
            "name": "GPT-OSS 120B",
            "origin": "OpenAI (Open Source)",
            "year": 2025,
            "lang": {"ca": "Multilingüe", "es": "Multilingüe", "en": "Multilingual"},
            "params": "120B",
            "disk_gb": 52.0,
            "ram_gb": 50,
            "description": {"ca": "Model obert d'OpenAI. Raonament avançat i agents. Apache 2.0.", "es": "Modelo abierto de OpenAI. Razonamiento avanzado y agentes. Apache 2.0.", "en": "OpenAI open model. Advanced reasoning and agents. Apache 2.0."},
            "mlx": "lmstudio-community/gpt-oss-120b-MLX-8bit",
            "ollama": "gpt-oss:120b",
            "gguf": None,
            "chat_format": "chatml",
            "prompt_tier": "full",
        },
        {
            "key": "mixtral",
            "name": "Mixtral 8x7B",
            "origin": "Mistral AI (França)",
            "year": 2023,
            "lang": {"ca": "Multilingüe", "es": "Multilingüe", "en": "Multilingual"},
            "params": "47B (MoE)",
            "disk_gb": 26,
            "ram_gb": 32,
            "description": {"ca": "Alta qualitat, model MoE eficient", "es": "Alta calidad, modelo MoE eficiente", "en": "High quality, efficient MoE model"},
            "mlx": "mlx-community/Mixtral-8x7B-Instruct-v0.1-4bit",
            "ollama": "mixtral:latest",
            "gguf": "https://huggingface.co/TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF/resolve/main/mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf",
            "chat_format": "chatml",  # 'mistral' no vàlid a llama.cpp; chatml suporta system msgs (RAG)
            "prompt_tier": "full",
        },
    ],
}
