"""
────────────────────────────────────
Server Nexe
Location: installer/installer_catalog_data.py
Description: Model catalog data (MODEL_CATALOG).
────────────────────────────────────
"""

# ═══════════════════════════════════════════════════════════════════════════
# MODEL CATALOG - Multiple options per category, including Catalan models
# Engines: mlx (Apple Silicon), ollama (universal)
# ═══════════════════════════════════════════════════════════════════════════
MODEL_CATALOG = {
    # ─────────────────────────────────────────────────────────────────────────
    # SMALL MODELS - For 8GB RAM machines
    # ─────────────────────────────────────────────────────────────────────────
    "small": [
        {
            "key": "qwen35_2b",
            "name": "Qwen3.5 2B",
            "origin": "Alibaba",
            "year": 2026,
            "lang": {"ca": "Multilingüe +100 idiomes", "es": "Multilingüe +100 idiomas", "en": "Multilingual +100 languages"},
            "params": "2B",
            "disk_gb": 1.5,
            "ram_gb": 2.0,
            "description": {"ca": "Multimodal, tool calling i thinking. Successor de Qwen3", "es": "Multimodal, tool calling y thinking. Sucesor de Qwen3", "en": "Multimodal, tool calling and thinking. Qwen3 successor"},
            "mlx": None,  # multimodal (vision_tower) incompatible amb mlx_lm text-only
            "ollama": "qwen3.5:2b",
            "gguf": None,
            "chat_format": "chatml",
            "prompt_tier": "small",
        },
        {
            "key": "phi35",
            "name": "Phi-3.5 Mini",
            "origin": "Microsoft",
            "year": 2024,
            "lang": {"ca": "Multilingüe (Anglès principal)", "es": "Multilingüe (Inglés principal)", "en": "Multilingual (English primary)"},
            "params": "3.8B",
            "disk_gb": 2.4,
            "ram_gb": 3.5,
            "description": {"ca": "Molt ràpid, bo per tasques generals", "es": "Muy rápido, bueno para tareas generales", "en": "Very fast, good for general tasks"},
            "mlx": "mlx-community/Phi-3.5-mini-instruct-4bit",
            "ollama": "phi3:mini",
            "gguf": "https://huggingface.co/microsoft/Phi-3.5-mini-instruct-gguf/resolve/main/Phi-3.5-mini-instruct-Q4_K_M.gguf",
            "chat_format": "chatml",
            "prompt_tier": "small",
        },
        {
            "key": "salamandra2b",
            "name": "Salamandra 2B",
            "origin": "BSC/AINA (Catalunya)",
            "year": 2025,
            "lang": {"ca": "Català, Castellà, Euskera, Gallec", "es": "Catalán, Castellano, Euskera, Gallego", "en": "Catalan, Spanish, Basque, Galician"},
            "params": "2B",
            "disk_gb": 1.5,
            "ram_gb": 2.5,
            "description": {"ca": "Optimitzat per llengües ibèriques", "es": "Optimizado para lenguas ibéricas", "en": "Optimized for Iberian languages"},
            "mlx": None,
            "ollama": "hdnh2006/salamandra-2b-instruct",
            "gguf": None,
            "chat_format": "chatml",
            "prompt_tier": "small",
        },
        {
            "key": "qwen35_4b",
            "name": "Qwen3.5 4B",
            "origin": "Alibaba",
            "year": 2026,
            "lang": {"ca": "Multilingüe (excel·lent català)", "es": "Multilingüe (excelente catalán)", "en": "Multilingual (excellent Catalan)"},
            "params": "4B",
            "disk_gb": 3.4,
            "ram_gb": 4.0,
            "description": {"ca": "Multimodal, tool calling, thinking. Ideal per Macs amb 8 GB", "es": "Multimodal, tool calling, thinking. Ideal para Macs con 8 GB", "en": "Multimodal, tool calling, thinking. Ideal for 8 GB Macs"},
            "mlx": None,  # multimodal (vision_tower) incompatible amb mlx_lm text-only
            "ollama": "qwen3.5:4b",
            "gguf": None,
            "chat_format": "chatml",
            "prompt_tier": "small",
        },
    ],
    # ─────────────────────────────────────────────────────────────────────────
    # MEDIUM MODELS - For 12-16GB RAM machines
    # ─────────────────────────────────────────────────────────────────────────
    "medium": [
        {
            "key": "mistral7b",
            "name": "Mistral 7B",
            "origin": "Mistral AI (França)",
            "year": 2023,
            "lang": {"ca": "Multilingüe", "es": "Multilingüe", "en": "Multilingual"},
            "params": "7B",
            "disk_gb": 4.1,
            "ram_gb": 5.5,
            "description": {"ca": "Excel·lent equilibri qualitat/velocitat", "es": "Excelente equilibrio calidad/velocidad", "en": "Excellent quality/speed balance"},
            "mlx": "mlx-community/Mistral-7B-Instruct-v0.3-4bit",
            "ollama": "mistral:latest",
            "gguf": "https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GGUF/resolve/main/mistral-7b-instruct-v0.2.Q4_K_M.gguf",
            "chat_format": "chatml",  # 'mistral' no vàlid a llama.cpp; chatml suporta system msgs (RAG)
            "prompt_tier": "full",
        },
        {
            "key": "salamandra7b",
            "name": "Salamandra 7B",
            "origin": "BSC/AINA (Catalunya)",
            "year": 2025,
            "lang": {"ca": "Català, Castellà, Euskera, Gallec", "es": "Catalán, Castellano, Euskera, Gallego", "en": "Catalan, Spanish, Basque, Galician"},
            "params": "7B",
            "disk_gb": 4.9,
            "ram_gb": 6.5,
            "description": {"ca": "El millor per català i llengües ibèriques", "es": "El mejor para catalán y lenguas ibéricas", "en": "Best for Catalan and Iberian languages"},
            "mlx": None,
            "ollama": "hdnh2006/salamandra-7b-instruct:q4_K_M",  # testat i verificat
            "gguf": "https://huggingface.co/cstr/salamandra-7b-instruct-GGUF/resolve/main/salamandra-7b-instruct-Q4_K_M.gguf",
            "chat_format": "chatml",
            "prompt_tier": "full",
        },
        {
            "key": "gemma3_12b",
            "name": "Gemma 3 12B",
            "origin": "Google DeepMind",
            "year": 2025,
            "lang": {"ca": "Multilingüe (excel·lent català)", "es": "Multilingüe (excelente catalán)", "en": "Multilingual (excellent Catalan)"},
            "params": "12B",
            "disk_gb": 7.0,
            "ram_gb": 9.0,
            "description": {"ca": "Molt bon seguiment d'instruccions i RAG", "es": "Muy buen seguimiento de instrucciones y RAG", "en": "Excellent instruction following and RAG"},
            "mlx": "mlx-community/gemma-3-12b-it-4bit",
            "ollama": "gemma3:12b",
            "gguf": None,
            "chat_format": "chatml",
            "prompt_tier": "full",
        },
        {
            "key": "qwen35_9b",
            "name": "Qwen3.5 9B",
            "origin": "Alibaba",
            "year": 2026,
            "lang": {"ca": "Multilingüe (excel·lent català)", "es": "Multilingüe (excelente catalán)", "en": "Multilingual (excellent Catalan)"},
            "params": "9B",
            "disk_gb": 6.6,
            "ram_gb": 8.0,
            "description": {"ca": "Multimodal, thinking, tool calling. Millor relacio qualitat/mida de la familia. Apache 2.0", "es": "Multimodal, thinking, tool calling. Mejor relacion calidad/tamaño de la familia. Apache 2.0", "en": "Multimodal, thinking, tool calling. Best quality/size ratio of the family. Apache 2.0"},
            "mlx": None,  # multimodal (vision_tower) incompatible amb mlx_lm text-only
            "ollama": "qwen3.5:9b",
            "gguf": None,
            "chat_format": "chatml",
            "prompt_tier": "full",
        },
    ],
    # ─────────────────────────────────────────────────────────────────────────
    # LARGE MODELS - For 32GB+ RAM machines
    # ─────────────────────────────────────────────────────────────────────────
    "large": [
        {
            "key": "qwen35_27b",
            "name": "Qwen3.5 27B",
            "origin": "Alibaba",
            "year": 2026,
            "lang": {"ca": "Multilingüe (excel·lent català)", "es": "Multilingüe (excelente catalán)", "en": "Multilingual (excellent Catalan)"},
            "params": "27B",
            "disk_gb": 17.0,
            "ram_gb": 20,
            "description": {"ca": "Multimodal complet, thinking avançat, tool calling. El millor Qwen per RAG i català. Apache 2.0", "es": "Multimodal completo, thinking avanzado, tool calling. El mejor Qwen para RAG y catalán. Apache 2.0", "en": "Full multimodal, advanced thinking, tool calling. Best Qwen for RAG and Catalan. Apache 2.0"},
            "mlx": None,  # multimodal (vision_tower) incompatible amb mlx_lm text-only
            "ollama": "qwen3.5:27b",
            "gguf": None,
            "chat_format": "chatml",
            "prompt_tier": "full",
        },
        {
            "key": "gemma3_27b",
            "name": "Gemma 3 27B",
            "origin": "Google DeepMind",
            "year": 2025,
            "lang": {"ca": "Multilingüe (excel·lent català)", "es": "Multilingüe (excelente catalán)", "en": "Multilingual (excellent Catalan)"},
            "params": "27B",
            "disk_gb": 16.2,
            "ram_gb": 20,
            "description": {"ca": "Excel·lent memòria RAG i català. Testat i recomanat", "es": "Excelente memoria RAG y catalán. Testado y recomendado", "en": "Excellent RAG memory and Catalan. Tested and recommended"},
            "mlx": "mlx-community/gemma-3-27b-it-4bit",
            "ollama": "gemma3:27b",
            "gguf": None,
            "chat_format": "chatml",
            "prompt_tier": "full",
        },
        {
            "key": "gpt_oss_20b",
            "name": "GPT-OSS 20B",
            "origin": "OpenAI (Open Source)",
            "year": 2025,
            "lang": {"ca": "Multilingüe", "es": "Multilingüe", "en": "Multilingual"},
            "params": "21B (MoE, 3.6B actius)",
            "disk_gb": 22.2,
            "ram_gb": 24,
            "description": {"ca": "Model obert d'OpenAI, MoE eficient. Llicència Apache 2.0", "es": "Modelo abierto de OpenAI, MoE eficiente. Licencia Apache 2.0", "en": "OpenAI open model, efficient MoE. Apache 2.0 license"},
            "mlx": "lmstudio-community/gpt-oss-20b-MLX-8bit",
            "ollama": "gpt-oss:20b",
            "gguf": None,
            "chat_format": "chatml",
            "prompt_tier": "full",
        },
        {
            "key": "qwen25_32b",
            "name": "Qwen2.5 32B",
            "origin": "Alibaba",
            "year": 2024,
            "lang": {"ca": "Multilingüe (excel·lent multi-idioma)", "es": "Multilingüe (excelente multi-idioma)", "en": "Multilingual (excellent multi-language)"},
            "params": "32B",
            "disk_gb": 19.0,
            "ram_gb": 22,
            "description": {"ca": "Excel·lent en multi-idioma i seguiment d'instruccions", "es": "Excelente en multi-idioma y seguimiento de instrucciones", "en": "Excellent multilingual and instruction following"},
            "mlx": "mlx-community/Qwen2.5-32B-Instruct-4bit",
            "ollama": "qwen2.5:32b",
            "gguf": "https://huggingface.co/bartowski/Qwen2.5-32B-Instruct-GGUF/resolve/main/Qwen2.5-32B-Instruct-Q4_K_M.gguf",
            "chat_format": "chatml",
            "prompt_tier": "full",
        },
        {
            "key": "qwq_32b",
            "name": "QwQ 32B",
            "origin": "Alibaba",
            "year": 2025,
            "lang": {"ca": "Multilingüe (raonament avançat)", "es": "Multilingüe (razonamiento avanzado)", "en": "Multilingual (advanced reasoning)"},
            "params": "32B",
            "disk_gb": 19.0,
            "ram_gb": 22,
            "description": {"ca": "Especialitzat en raonament — pensa pas a pas. Compita amb models molt més grans", "es": "Especializado en razonamiento — piensa paso a paso. Compite con modelos mucho más grandes", "en": "Reasoning specialist — thinks step by step. Competes with much larger models"},
            "mlx": None,
            "ollama": "qwq:32b",
            "gguf": None,
            "chat_format": "chatml",
            "prompt_tier": "full",
        },
        {
            "key": "deepseek_r1_32b",
            "name": "DeepSeek R1 32B",
            "origin": "DeepSeek AI (Xina)",
            "year": 2025,
            "lang": {"ca": "Multilingüe (raonament avançat)", "es": "Multilingüe (razonamiento avanzado)", "en": "Multilingual (advanced reasoning)"},
            "params": "32B",
            "disk_gb": 19.0,
            "ram_gb": 22,
            "description": {"ca": "Model de raonament — pensa abans de respondre. Ideal per anàlisi i documents", "es": "Modelo de razonamiento — piensa antes de responder. Ideal para análisis y documentos", "en": "Reasoning model — thinks before answering. Ideal for analysis and documents"},
            "mlx": "mlx-community/DeepSeek-R1-Distill-Qwen-32B-4bit",
            "ollama": "deepseek-r1:32b",
            "gguf": "https://huggingface.co/bartowski/DeepSeek-R1-Distill-Qwen-32B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-32B-Q4_K_M.gguf",
            "chat_format": "chatml",
            "prompt_tier": "full",
        },
        {
            "key": "mixtral",
            "name": "Mixtral 8x7B",
            "origin": "Mistral AI (França)",
            "year": 2023,
            "lang": {"ca": "Multilingüe", "es": "Multilingüe", "en": "Multilingual"},
            "params": "47B (MoE)",
            "disk_gb": 26,
            "ram_gb": 32,
            "description": {"ca": "Alta qualitat, model MoE eficient", "es": "Alta calidad, modelo MoE eficiente", "en": "High quality, efficient MoE model"},
            "mlx": "mlx-community/Mixtral-8x7B-Instruct-v0.1-4bit",
            "ollama": "mixtral:latest",
            "gguf": "https://huggingface.co/TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF/resolve/main/mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf",
            "chat_format": "chatml",  # 'mistral' no vàlid a llama.cpp; chatml suporta system msgs (RAG)
            "prompt_tier": "full",
        },
    ],
}
